---
apiVersion: v1
kind: Secret        
metadata:
  namespace: default
  name: quay
data:
    .dockerconfigjson: >-
           eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoiaWxhbl9waW50byIsInBhc3N3b3JkIjoiYnA3MjAzMzkiLCJhdXRoIjoiYVd4aGJsOXdhVzUwYnpwaWNEY3lNRE16T1E9PSIsImVtYWlsIjoiIn19fQ==
type: kubernetes.io/dockerconfigjson  
annotations:
     tekton.dev/docker-0: quay.io
---     
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: my-sa
secrets:
- name: quay
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: default  
spec: 
  type: ClusterIP
  ports:
  - name: http-listener
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      serviceAccountName: my-sa
      containers:
        - name: hello-world
          image: quay.io/ilan_pinto/hello-world:v1
          ports:
            - containerPort: 5000
